version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  praca inzynierska ci:
    jobs:
      - gui_tools tests


jobs:
  gui_tools tests:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Canvas controller test
          command: |
            py.test --junitxml tests/reports/res_canvas_controller.xml tests/ut_canvas_controller.py
            coverage run tests/ut_canvas_controller.py
            coverage report > tests/reports/coverage/canvas_controller.cov
      - run:
          name: Log test
          command: |
            py.test --junitxml tests/reports/res_log.xml tests/ut_logger.py
            coverage run tests/ut_logger.py
            coverage report > tests/reports/coverage/logger.cov
      - run:
          name: Data Utils test
          command: |
            py.test --junitxml tests/reports/res_data_utils.xml tests/ut_data_utils.py
            coverage run tests/ut_data_utils.py
            coverage report > tests/reports/coverage/data_utils.cov
      - run:
          name: File validator test
          command: |
            py.test --junitxml tests/reports/res_filevalidator.xml tests/ut_FileValidator.py
            coverage run tests/ut_FileValidator.py
            coverage report > tests/reports/coverage/file_validator.cov
      - store_artifacts:
          path: tests/reports/coverage
      - store_test_results:
          path: tests/reports
